# Generated by Django 3.1.1 on 2020-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='photos')),
                ('img2', models.ImageField(upload_to='photos')),
                ('img3', models.ImageField(upload_to='photos')),
                ('img4', models.ImageField(upload_to='photos')),
                ('img5', models.ImageField(upload_to='photos')),
                ('img6', models.ImageField(null=True, upload_to='photos')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=20, verbose_name='ЦЕНА')),
                ('pred1', models.CharField(max_length=255, verbose_name='Диагональ дисплея, дюйм')),
                ('pred2', models.CharField(max_length=255, verbose_name='Разрешение дисплея')),
                ('pred3', models.CharField(max_length=255, verbose_name='Операционная система')),
                ('pred4', models.CharField(max_length=255, verbose_name='Объем оперативной памяти')),
                ('pred5', models.CharField(max_length=255, verbose_name='Объём встроенной памяти')),
                ('pred6', models.CharField(max_length=255, verbose_name='Количество SIM-карт')),
                ('pred7', models.CharField(max_length=255, verbose_name='Стандарт связи')),
                ('pred8', models.CharField(max_length=255, verbose_name='Стандарт защиты от пыли и влаги')),
                ('Seria1', models.CharField(max_length=255, verbose_name='Серия Основные характеристики')),
                ('Seria2', models.CharField(max_length=255, verbose_name='Модельный год Основные характеристики')),
                ('Seria3', models.CharField(max_length=255, verbose_name='Число пикселей на дюйм (PPI)  Дисплей')),
                ('Seria4', models.CharField(max_length=255, verbose_name='Разрешение дисплея Дисплей')),
                ('Seria5', models.CharField(max_length=255, verbose_name='Диагональ дисплея, дюйм Дисплей')),
                ('Seria6', models.CharField(max_length=255, verbose_name='Тип матрицы Дисплей')),
                ('Seria7', models.CharField(max_length=255, verbose_name='Производитель процессора  Процессор')),
                ('Seria8', models.CharField(max_length=255, verbose_name='Операционная система Процессор')),
                ('Seria9', models.CharField(max_length=255, verbose_name='A13 Bionic Процессор')),
                ('Seria10', models.CharField(max_length=255, verbose_name='Максимальный объем поддерживаемой карты памяти Память')),
                ('Seria11', models.CharField(max_length=255, verbose_name='Объем оперативной памяти Память')),
                ('Seria12', models.CharField(max_length=255, verbose_name='Объём встроенной памяти Память')),
                ('Seria13', models.CharField(max_length=255, verbose_name='Количество SIM-карт SIM-карта')),
                ('Seria14', models.CharField(max_length=255, verbose_name='Размер SIM-карт SIM-карта')),
                ('Seria15', models.CharField(max_length=255, verbose_name='Встроенная вспышка Основная камера')),
                ('Seria16', models.CharField(max_length=255, verbose_name='Количество мегапикселей Основная камера')),
                ('Seria17', models.CharField(max_length=255, verbose_name='Дополнительно Основная камера')),
                ('Seria18', models.CharField(max_length=255, verbose_name='Светосила второго модуля Основная камера')),
                ('Seria19', models.CharField(max_length=255, verbose_name='Автофокус Основная камера')),
                ('Seria20', models.CharField(max_length=255, verbose_name='Светосила Основная камера')),
                ('Seria21', models.CharField(max_length=255, verbose_name='Тип первого модуля Основная камера')),
                ('Seria22', models.CharField(max_length=255, verbose_name='Запись видео камеры Основная камера')),
                ('Seria23', models.CharField(max_length=255, verbose_name='Тип второго модуля Основная камера')),
                ('Seria24', models.CharField(max_length=255, verbose_name='Размер пикселя, мкм Основная камера')),
                ('Seria25', models.CharField(max_length=255, verbose_name='Стабилизация Основная камера')),
                ('Seria26', models.CharField(max_length=255, verbose_name='Количество мегапикселей второго модуля Основная камера')),
                ('Seria27', models.CharField(max_length=255, verbose_name='СветосилаФР Фронтальная камера')),
                ('Seria28', models.CharField(max_length=255, verbose_name='Автофокус Фронтальная камера')),
                ('Seria29', models.CharField(max_length=255, verbose_name='Стабилизация Фронтальная камера')),
                ('Seria30', models.CharField(max_length=255, verbose_name='Запись видео камеры Фронтальная камера')),
                ('Seria31', models.CharField(max_length=255, verbose_name='ДополнительноФР Фронтальная камера')),
                ('Seria32', models.CharField(max_length=255, verbose_name='Количество мегапикселей Фронтальная камера')),
                ('Seria33', models.CharField(max_length=255, verbose_name='Навигация Связь')),
                ('Seria34', models.CharField(max_length=255, verbose_name='Разъёмы Связь')),
                ('Seria35', models.CharField(max_length=255, verbose_name='Интерфейсы Связь')),
                ('Seria36', models.CharField(max_length=255, verbose_name='Стандарт связи Связь')),
                ('Seria37', models.CharField(max_length=255, verbose_name='Время работы в режиме разговора, ч Питания')),
                ('Seria38', models.CharField(max_length=255, verbose_name='Возможность беспроводной зарядки Питания')),
                ('Seria40', models.CharField(max_length=255, verbose_name='Ёмкость аккумулятора, mAh Питания')),
                ('Seria41', models.CharField(max_length=255, verbose_name='Быстрая зарядка  Питания')),
                ('Seria42', models.CharField(max_length=255, verbose_name='Материал корпуса Функции и особенности')),
                ('Seria43', models.CharField(max_length=255, verbose_name='Особенности Функции и особенности')),
                ('Seria44', models.CharField(max_length=255, verbose_name='Стандарт защиты от пыли и влаги Функции и особенности')),
                ('Seria45', models.CharField(max_length=255, verbose_name='Датчики Функции и особенности')),
                ('Seria46', models.CharField(max_length=255, verbose_name='Толщина, мм Габариты')),
                ('Seria47', models.CharField(max_length=255, verbose_name='Ширина, мм Габариты')),
                ('Seria48', models.CharField(max_length=255, verbose_name='Вес, гр Габариты')),
                ('Seria49', models.CharField(max_length=255, verbose_name='Высота, мм Габариты')),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
