# Generated by Django 3.1.1 on 2020-10-25 16:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0002_auto_20201025_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
