# Generated by Django 3.1.1 on 2020-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0007_auto_20201030_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='цена'),
        ),
    ]
