# Generated by Django 3.1.1 on 2020-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0008_auto_20201124_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.CharField(max_length=20, verbose_name='ЦЕНА'),
        ),
    ]
