# Generated by Django 3.1.1 on 2020-11-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0009_auto_20201124_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='genres',
            field=models.ManyToManyField(to='MDShop.Genre', verbose_name='жанры'),
        ),
    ]
