# Generated by Django 3.1.1 on 2020-11-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0010_auto_20201124_0257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={},
        ),
    ]
