# Generated by Django 3.1.1 on 2020-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0011_auto_20201124_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Razdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
