# Generated by Django 3.1.4 on 2021-01-02 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0014_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likefov', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MDShop.smartphone')),
            ],
        ),
    ]
