# Generated by Django 3.1.4 on 2021-01-02 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0016_customer_likecus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MDShop.like'),
        ),
    ]
