# Generated by Django 3.1.4 on 2021-01-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0017_auto_20210102_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MDShop.like'),
        ),
    ]
