# Generated by Django 3.1.4 on 2021-01-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0020_auto_20210103_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ManyToManyField(default=1, null=True, to='MDShop.smartphone'),
        ),
    ]
