# Generated by Django 3.1.4 on 2021-01-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0021_auto_20210103_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ManyToManyField(null=True, to='MDShop.smartphone', verbose_name='b'),
        ),
    ]
