# Generated by Django 3.1.4 on 2021-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0025_auto_20210121_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ManyToManyField(null=True, to='MDShop.smartphone', verbose_name='b'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
