# Generated by Django 3.1.4 on 2021-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0029_auto_20210121_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
            preserve_default=False,
        ),
    ]
