# Generated by Django 3.1.4 on 2021-01-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0034_auto_20210122_0157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'ordering': ['title']},
        ),
    ]
