# Generated by Django 3.1.4 on 2021-01-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0035_auto_20210122_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'ordering': ['-id']},
        ),
    ]
