# Generated by Django 3.1.4 on 2021-01-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0038_auto_20210130_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id']},
        ),
    ]
