# Generated by Django 3.1.4 on 2021-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0040_auto_20210131_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ManyToManyField(blank=True, null=True, to='MDShop.like', verbose_name='лайк'),
        ),
    ]
