# Generated by Django 3.1.4 on 2021-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0041_auto_20210202_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='likecus',
            field=models.ManyToManyField(blank=True, null=True, to='MDShop.smartphone', verbose_name='лайк'),
        ),
    ]
