# Generated by Django 3.1.4 on 2021-02-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0043_auto_20210202_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likecus', models.ManyToManyField(to='MDShop.smartphone', verbose_name='лайк')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='likeCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customerlike'),
        ),
    ]
