# Generated by Django 3.1.4 on 2021-02-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0046_auto_20210203_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlike',
            name='like',
            field=models.ManyToManyField(to='MDShop.smartphone', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='customerlike',
            name='likeCustomer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer'),
            preserve_default=False,
        ),
    ]
