# Generated by Django 3.1.4 on 2021-02-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0054_auto_20210203_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlike',
            name='likeCustomer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer'),
        ),
    ]
