# Generated by Django 3.1.4 on 2021-02-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0061_auto_20210210_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('house', models.CharField(max_length=30)),
                ('apartment', models.CharField(max_length=30)),
                ('index', models.CharField(max_length=30)),
                ('addressCustomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
            ],
        ),
    ]
