# Generated by Django 3.1.4 on 2021-02-09 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0062_customeraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeraddress',
            options={'ordering': ['-id']},
        ),
    ]
