# Generated by Django 3.1.4 on 2021-02-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0064_auto_20210210_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orederPrice', models.CharField(max_length=30)),
                ('orderAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customeraddress')),
                ('orderCustomer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
                ('orderProduct', models.ManyToManyField(to='MDShop.smartphone')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
