# Generated by Django 3.1.4 on 2021-02-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0065_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
