# Generated by Django 3.1.4 on 2021-02-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0066_auto_20210211_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderProduct',
            new_name='smartphone',
        ),
    ]
