# Generated by Django 3.1.4 on 2021-02-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0067_auto_20210211_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orederPrice',
        ),
    ]
