# Generated by Django 3.1.4 on 2021-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0068_remove_order_orederprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveSmallIntegerField(default=True, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
