# Generated by Django 3.1.4 on 2021-02-12 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0071_auto_20210213_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
