# Generated by Django 3.1.4 on 2021-02-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0074_populargoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populargoods',
            name='top1',
        ),
    ]
