# Generated by Django 3.1.4 on 2021-02-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0075_remove_populargoods_top1'),
    ]

    operations = [
        migrations.AddField(
            model_name='populargoods',
            name='top1',
            field=models.ManyToManyField(blank=True, max_length=6, to='MDShop.smartphone'),
        ),
    ]
