# Generated by Django 3.1.4 on 2021-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0076_populargoods_top1'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='Seria1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Серия Основные характеристики'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria10',
            field=models.CharField(blank=True, max_length=255, verbose_name='Максимальный объем поддерживаемой карты памяти Память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria11',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объем оперативной памяти Память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria12',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объём встроенной памяти Память'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria13',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество SIM-карт SIM-карта'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria14',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размер SIM-карт SIM-карта'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria15',
            field=models.CharField(blank=True, max_length=255, verbose_name='Встроенная вспышка Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria16',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество мегапикселей Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria17',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительно Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria18',
            field=models.CharField(blank=True, max_length=255, verbose_name='Светосила второго модуля Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria19',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автофокус Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Модельный год Основные характеристики'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria20',
            field=models.CharField(blank=True, max_length=255, verbose_name='Светосила Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria21',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип первого модуля Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria22',
            field=models.CharField(blank=True, max_length=255, verbose_name='Запись видео камеры Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria23',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип второго модуля Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria24',
            field=models.CharField(blank=True, max_length=255, verbose_name='Размер пикселя, мкм Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria25',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стабилизация Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria26',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество мегапикселей второго модуля Основная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria27',
            field=models.CharField(blank=True, max_length=255, verbose_name='СветосилаФР Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria28',
            field=models.CharField(blank=True, max_length=255, verbose_name='Автофокус Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria29',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стабилизация Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Число пикселей на дюйм (PPI)  Дисплей'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria30',
            field=models.CharField(blank=True, max_length=255, verbose_name='Запись видео камеры Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria31',
            field=models.CharField(blank=True, max_length=255, verbose_name='ДополнительноФР Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria32',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество мегапикселей Фронтальная камера'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria33',
            field=models.CharField(blank=True, max_length=255, verbose_name='Навигация Связь'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria34',
            field=models.CharField(blank=True, max_length=255, verbose_name='Разъёмы Связь'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria35',
            field=models.CharField(blank=True, max_length=255, verbose_name='Интерфейсы Связь'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria36',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стандарт связи Связь'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria37',
            field=models.CharField(blank=True, max_length=255, verbose_name='Время работы в режиме разговора, ч Питания'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria38',
            field=models.CharField(blank=True, max_length=255, verbose_name='Возможность беспроводной зарядки Питания'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Разрешение дисплея Дисплей'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria40',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ёмкость аккумулятора, mAh Питания'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria41',
            field=models.CharField(blank=True, max_length=255, verbose_name='Быстрая зарядка  Питания'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria42',
            field=models.CharField(blank=True, max_length=255, verbose_name='Материал корпуса Функции и особенности'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria43',
            field=models.CharField(blank=True, max_length=255, verbose_name='Особенности Функции и особенности'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria44',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стандарт защиты от пыли и влаги Функции и особенности'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria45',
            field=models.CharField(blank=True, max_length=255, verbose_name='Датчики Функции и особенности'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria46',
            field=models.CharField(blank=True, max_length=255, verbose_name='Толщина, мм Габариты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria47',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ширина, мм Габариты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria48',
            field=models.CharField(blank=True, max_length=255, verbose_name='Вес, гр Габариты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria49',
            field=models.CharField(blank=True, max_length=255, verbose_name='Высота, мм Габариты'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Диагональ дисплея, дюйм Дисплей'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тип матрицы Дисплей'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria7',
            field=models.CharField(blank=True, max_length=255, verbose_name='Производитель процессора  Процессор'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria8',
            field=models.CharField(blank=True, max_length=255, verbose_name='Операционная система Процессор'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='Seria9',
            field=models.CharField(blank=True, max_length=255, verbose_name='A13 Bionic Процессор'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Диагональ дисплея, дюйм'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Разрешение дисплея'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объем оперативной памяти'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred5',
            field=models.CharField(blank=True, max_length=255, verbose_name='Объём встроенной памяти'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred6',
            field=models.CharField(blank=True, max_length=255, verbose_name='Количество SIM-карт'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred7',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стандарт связи'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='pred8',
            field=models.CharField(blank=True, max_length=255, verbose_name='Стандарт защиты от пыли и влаги'),
        ),
    ]
