# Generated by Django 3.1.4 on 2021-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0078_auto_20210214_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEnglish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUser', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('text', models.CharField(blank=True, max_length=233, null=True)),
            ],
        ),
    ]
