# Generated by Django 3.1.4 on 2021-03-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0079_customerenglish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
