# Generated by Django 3.1.4 on 2021-03-02 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0080_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='onHOLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=330)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='needsREVIEW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=330)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='inPROGRESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=330)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='APPROVED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=330)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
