# Generated by Django 3.1.4 on 2021-03-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0081_approved_inprogress_needsreview_onhold'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=330)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.customer')),
                ('genres', models.ManyToManyField(to='MDShop.Genre', verbose_name='жанры')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
