# Generated by Django 3.1.4 on 2021-03-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MDShop', '0084_auto_20210303_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodels',
            name='genr',
        ),
        migrations.AddField(
            model_name='testmodels',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MDShop.genre'),
        ),
    ]
